name: Test IoT Build Failure

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Test Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.OIDC_ROLE_AWS_REGION }}

    - name: Try to fail
      run: exit 1

    - name: Send Build Failure Notification to AWS IoT Topic
      if: ${{ failure() }}
      run: |
        aws iot-data publish \
          --topic t04glovern/github-builder \
          --region ap-southeast-2 \
          --cli-binary-format raw-in-base64-out \
          --payload '{"status":"FAILED", "repo":"${{ github.repository }}", "commit":"${{ github.sha }}"}'

    - name: Send Build Success Notification to AWS IoT Topic
      if: ${{ success() }}
      run: |
        aws iot-data publish \
          --topic t04glovern/github-builder \
          --region ap-southeast-2 \
          --cli-binary-format raw-in-base64-out \
          --payload '{"status":"SUCCESS", "repo":"${{ github.repository }}", "commit":"${{ github.sha }}"}'
